### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by M-amir097** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#4

**In which task and step of the codelab can this issue be found?**
rollButton.setOnClickListener {
           val toast = Toast.makeText(this, "Dice Rolled!", Toast.LENGTH_SHORT)
           toast.show()
       }

and 

Toast.makeText(this, "Dice Rolled!", Toast.LENGTH_SHORT).show()

**Describe the problem**

 A toast message did not pop up at the bottom of the screen

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  4.1.3
_API version of the emulator:_  Pixel 3 XL API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@M-amir097 
Thank you for reaching out to us. 
One of the solution is to try putting this line of code (Toast.makeText(this, "Dice Rolled!", Toast.LENGTH_SHORT).show()) in the onCreate() method of their activity? (Instead of putting it in the click listener). That can test whether the toast pops up at all in your app. Then if that works, you can put the Toast code back in the onclick listener. 
Happy coding!
